[package]
name = "wz"
version = "0.1.0"
edition = "2021"

[lib]
name = "wz"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
memmap = "0.7"
thiserror = "1"
crypto = { version = "0.1.0", path = "../crypto" }
