[package]
name = "wz"
version = "0.1.0"
edition = "2024"

[lib]
name = "wz"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
crypto = { version = "0.1.0", path = "../crypto" }
ego-tree = { version = "0.10.0" }
